Bump up testcafe version to v1.14.2
saucelabs/sauce-testcafe-runner pull request #94
Opened 2021-05-19 19:53 UTC by tianfeng92

Verified on saucectl-testcafe-example

2021-05-20 00:42 UTC, alexplischke requested changes
Missing https://github.com/saucelabs/sauce-testcafe-runner/blob/master/Dockerfile#L19

2021-05-20 15:23 UTC, alexplischke commented on Dockerfile
> +ENV TESTCAFE_VERSION=1.14.2
👍  TBH, it would be nice to find an alternative solution to having to specify the version in two places 😄

2021-05-20 15:23 UTC, alexplischke commented on Dockerfile
> -RUN chmod 777 -R /home/seluser/
If you are deleting this line, then you have the delete the comment above as well 💡

2021-05-20 23:46 UTC, FriggaHel commented on .github/workflows/release.yml
> +          echo $TESTCAFE_VERSION
I think we can remove that line ?

2021-05-20 23:48 UTC, FriggaHel approved these changes

2021-05-20 23:48 UTC, tianfeng92 commented on .github/workflows/release.yml
> +          echo $TESTCAFE_VERSION
removing!

2021-05-21 00:18 UTC, alexplischke approved these changes

2021-05-21 07:16 UTC, FriggaHel approved these changes

2021-05-21 15:21 UTC, merged